[package]
name = "wasm-rs-blog-web"
version = "0.1.0"
authors = ["deishy"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew-functional = { git = "https://github.com/yewstack/yew", rev = "f27e268"}
yew = { git = "https://github.com/yewstack/yew", rev = "f27e268"}
yew-router = { git = "https://github.com/yewstack/yew", rev = "f27e268"}
wasm-bindgen = "0.2.67"
